/* Deklarasi Fakta */
bentukKartu(merah, 0).
bentukKartu(kuning, 0).
bentukKartu(hijau, 0).
bentukKartu(biru, 0).
bentukKartu(merah, 1).
bentukKartu(kuning, 1).
bentukKartu(hijau, 1).
bentukKartu(biru, 1).
bentukKartu(merah, 2).
bentukKartu(kuning, 2).
bentukKartu(hijau, 2).
bentukKartu(biru, 2).
bentukKartu(merah, 3).
bentukKartu(kuning, 3).
bentukKartu(hijau, 3).
bentukKartu(biru, 3).
bentukKartu(merah, 4).
bentukKartu(kuning, 4).
bentukKartu(hijau, 4).
bentukKartu(biru, 4).
bentukKartu(merah, 5).
bentukKartu(kuning, 5).
bentukKartu(hijau, 5).
bentukKartu(biru, 5).
bentukKartu(merah, 6).
bentukKartu(kuning, 6).
bentukKartu(hijau, 6).
bentukKartu(biru, 6).
bentukKartu(merah, 7).
bentukKartu(kuning, 7).
bentukKartu(hijau, 7).
bentukKartu(biru, 7).
bentukKartu(merah, 8).
bentukKartu(kuning, 8).
bentukKartu(hijau, 8).
bentukKartu(biru, 8).
bentukKartu(merah, 9).
bentukKartu(kuning, 9).
bentukKartu(hijau, 9).
bentukKartu(biru, 9).
bentukKartu(merah, skip).
bentukKartu(kuning, skip).
bentukKartu(hijau, skip).
bentukKartu(biru, skip).
bentukKartu(merah, reverse).
bentukKartu(kuning, reverse).
bentukKartu(hijau, reverse).
bentukKartu(biru, reverse).
bentukKartu(merah, drawTwo).
bentukKartu(kuning, drawTwo).
bentukKartu(hijau, drawTwo).
bentukKartu(biru, drawTwo).
bentukKartu(hitam, wild).
bentukKartu(hitam, wildDrawFour).
